version: '2.7'
services:
  app:
    build:
      context: .
    volumes:
      - .:/my-app  
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm start    